from __future__ import annotations

import json
import re
from pathlib import Path
from typing import TYPE_CHECKING

from ai_slop_detector.state import (
    AggregateResult,
    CriticOutput,
    GuidelinesCriticOutput,
    GuidelinesFinding,
    SloppinessFeatures,
    Verdict,
)

if TYPE_CHECKING:
    from ai_slop_detector.claude_client import ClaudeClient
    from ai_slop_detector.rag import RAGIndex
    from ai_slop_detector.state import TriageState

# File extensions that indicate a documentation-only or config-only changeset.
# A PR touching only these is classified as trivial without calling Haiku.
# Covers: prose docs, images, common config formats, lock files, and files
# with no extension (LICENSE, NOTICE, AUTHORS, etc.).
_DOC_AND_CONFIG_SUFFIXES = {
    # Prose / documentation
    ".md", ".rst", ".txt", ".adoc",
    # Config / manifest (no executable logic)
    ".toml", ".yaml", ".yml", ".json", ".ini", ".cfg", ".conf",
    ".gitignore", ".gitattributes", ".editorconfig", ".prettierrc", ".eslintrc",
    # Assets
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".webp",
    # Lock files
    ".lock",
    # No extension — LICENSE, NOTICE, AUTHORS, Makefile variants, etc.
    "",
}

_CLASSIFY_SYSTEM = (
    "You are a PR size classifier. "
    "Classify the PR as exactly one of: small, medium, large.\n"
    "- small:  10–100 changed lines, focused single concern\n"
    "- medium: 100–500 changed lines, or multiple concerns\n"
    "- large:  500+ changed lines, or major architectural change\n"
    "Respond with exactly one word."
)

_CRITIC_SYSTEM = """\
You are a senior code reviewer assessing whether this PR follows the project's contributing guidelines.

SCORING RUBRIC — calibrate against these anchors:
  10 — Exemplary. Matches retrieved guidelines AND PR shows clear intent backed by the diff (tests, changelog, scoped commits).
   8 — Solid. Diff follows guidelines; only minor presentation / commit-message issues. THIS IS THE COMMON CASE for accepted PRs.
   6 — Some unclear or minor guideline misses, or genuinely empty retrieval context.
   4 — Multiple guideline misses (missing tests when project requires them, wrong commit format, undocumented public API).
   2 — Severe: ignores explicit project rules, no PR description, or tests absent for a behaviour change.
   0 — Bypasses the project entirely (reverts maintainer decisions, removes CI, force-merge attempt).

HARD CAPS (apply BEFORE the rubric):
- If retrieved context includes an AI-disclosure or AI-policy rule (e.g., "AI_POLICY", "disclose AI assistance")
  AND the PR body contains an AI-generation footer ("Generated with Claude Code", "Prepared with Codex",
  "🤖" bot emoji, "Generated by GPT"), AND the PR body does NOT explicitly disclose AI assistance per the policy
  → cap score at 4 with finding {"severity":"major","category":"ai_policy"}.
- If retrieved context explicitly requires tests for behaviour changes and the diff adds NO test files
  for a behaviour change → cap at 4.

DEFAULT POSTURE:
- If retrieved context is genuinely empty (no chunks at all), return 6 — no basis to judge.
- If chunks were retrieved and the PR is consistent with them, score 7–9 (common case).
- Reserve 10 for PRs with positive exemplary signals (tests + docs + scoped commit + clear motivation).
- Do not assume a hidden violation when you cannot point to one in retrieved context.

OUTPUT FORMAT — strict:
Return ONLY a single JSON object, no markdown fences, no prose, no trailing text.
Escape backslashes and quotes inside string values. Keep "evidence" as a one-line paraphrase.

Schema:
{
  "score": <integer 0-10>,
  "findings": [
    {"severity": "critical"|"major"|"minor"|"info", "category": "<slug>", "evidence": "<one-line paraphrase>"}
  ],
  "citations": ["<chunk_id_string>"]
}
"""


# ------------------------------------------------------------------
# Node: ingest_pr
# ------------------------------------------------------------------

def ingest_pr_node(state: TriageState) -> dict:
    """Validates that required data is present; no data fetching happens here."""
    if state.metadata is None:
        raise ValueError("ingest_pr: state.metadata is missing")
    return {}


# ------------------------------------------------------------------
# Node: classify_size
# ------------------------------------------------------------------

def classify_size_node(state: TriageState, claude: ClaudeClient) -> dict:
    """Classify PR size as trivial / small / medium / large.

    Two heuristics short-circuit to 'trivial' before any LLM call:
    1. additions + deletions < 10 — genuinely tiny changesets.
    2. All changed files are docs/config only (.md, .rst, .txt, .gitignore,
       LICENSE, etc.) — no code changed so guidelines critique adds no value.
    Otherwise Haiku decides between small / medium / large by reading the diff
    summary and file list.
    """
    if _is_trivial(state):
        return {"size_classification": "trivial"}

    meta = state.metadata
    files_preview = "\n".join(state.files_changed[:30])
    diff_preview = (state.raw_diff or "")[:3000]

    user_msg = (
        f"PR: {meta.title}\n"
        f"{meta.additions} additions, {meta.deletions} deletions across {meta.changed_files} files\n\n"
        f"Files changed:\n{files_preview}\n\n"
        f"Diff (first 3000 chars):\n{diff_preview}"
    )

    from ai_slop_detector.claude_client import MODEL_HAIKU

    raw = claude.complete(
        messages=[{"role": "user", "content": user_msg}],
        model=MODEL_HAIKU,
        max_tokens=16,
        system=_CLASSIFY_SYSTEM,
    )
    size = raw.strip().lower()
    if size not in {"small", "medium", "large"}:
        size = "medium"  # safe fallback if Haiku returns unexpected text
    return {"size_classification": size}


def _is_trivial(state: TriageState) -> bool:
    total_lines = state.metadata.additions + state.metadata.deletions
    if total_lines < 10:
        return True
    if state.files_changed and all(
        Path(f).suffix.lower() in _DOC_AND_CONFIG_SUFFIXES
        for f in state.files_changed
    ):
        return True
    return False


# ------------------------------------------------------------------
# Node: retrieve_context
# ------------------------------------------------------------------

def retrieve_context_node(state: TriageState, rag: RAGIndex) -> dict:
    """Query ChromaDB for the top-8 chunks most relevant to this PR."""
    query = f"{state.metadata.title}\n{state.metadata.body or ''}\n{' '.join(state.files_changed[:10])}"
    chunks = rag.retrieve(state.repo, query, top_k=8)
    return {"rag_chunks": chunks}


# ------------------------------------------------------------------
# Node: guidelines_critic
# ------------------------------------------------------------------

def guidelines_critic_node(state: TriageState, claude: ClaudeClient, *, model: str | None = None) -> dict:
    """Guidelines critic — Sonnet in production, overridable for eval."""
    from ai_slop_detector.claude_client import MODEL_SONNET

    chunks_text = "\n\n".join(state.rag_chunks) if state.rag_chunks else "(no guideline context retrieved)"
    diff_preview = (state.raw_diff or "")[:6000]

    user_msg = (
        f"PR #{state.metadata.number}: {state.metadata.title}\n\n"
        f"PR Description:\n{state.metadata.body or '(none)'}\n\n"
        f"Diff (first 6000 chars):\n{diff_preview}\n\n"
        f"Retrieved guideline context:\n{chunks_text}"
    )

    raw = claude.complete(
        messages=[{"role": "user", "content": user_msg}],
        model=model or MODEL_SONNET,
        max_tokens=2048,
        system=_CRITIC_SYSTEM,
    )

    details = _parse_critic_json(raw)
    score = details.score
    verdict_str = "pass" if score >= 8 else "needs_review" if score >= 5 else "fail"

    output = CriticOutput(
        critic_name="guidelines_critic",
        verdict=verdict_str,
        reasoning=f"Score {score}/10 with {len(details.findings)} finding(s).",
        confidence=score / 10.0,
        details=details,
    )
    return {"critic_outputs": [output]}


def _parse_critic_json(raw: str) -> GuidelinesCriticOutput:
    """Extract and parse the JSON block the critic is expected to return.

    Handles the four observed failure modes:
    - Markdown fences around the JSON (despite being told not to).
    - Prose before or after the JSON block ("Extra data" error).
    - Invalid backslash escapes inside evidence strings.
    - Citations returned as list-of-dicts instead of list-of-strings.
    """
    data = _extract_json(raw)
    if data is None:
        raise ValueError(f"critic returned unparseable JSON:\n{raw[:500]}")

    findings = [
        GuidelinesFinding(
            severity=f.get("severity", "info"),
            category=f.get("category", "unknown"),
            evidence=f.get("evidence", ""),
        )
        for f in data.get("findings", [])
        if isinstance(f, dict)
    ]
    raw_citations = data.get("citations", []) or []
    citations = [
        c.get("text") or c.get("evidence") or c.get("chunk_id") or str(c)
        if isinstance(c, dict) else str(c)
        for c in raw_citations
    ]
    return GuidelinesCriticOutput(
        score=int(data.get("score", 5)),
        findings=findings,
        citations=citations,
    )


def _extract_json(raw: str) -> dict | None:
    """Try several recovery strategies to pull a JSON object out of raw model output."""
    text = raw.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    attempts: list[str] = [text]

    # Extract the largest balanced {...} block (handles prose before/after).
    block = _largest_brace_block(text)
    if block and block != text:
        attempts.append(block)

    # Neutralise invalid backslash escapes in the candidate(s).
    fixed = [_fix_bad_escapes(a) for a in attempts]
    attempts.extend(a for a in fixed if a not in attempts)

    for candidate in attempts:
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            continue
    return None


def _largest_brace_block(text: str) -> str | None:
    """Return the substring from the first '{' to its matching '}', ignoring braces in strings."""
    start = text.find("{")
    if start == -1:
        return None
    depth = 0
    in_string = False
    escape = False
    for i in range(start, len(text)):
        ch = text[i]
        if escape:
            escape = False
            continue
        if ch == "\\":
            escape = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    return None


def _fix_bad_escapes(text: str) -> str:
    """Double-up backslashes that aren't part of a valid JSON escape sequence."""
    return re.sub(r'\\(?!["\\/bfnrtu])', r"\\\\", text)


# ------------------------------------------------------------------
# Node: architecture_critic (B1)
# ------------------------------------------------------------------

_ARCH_CRITIC_SYSTEM = """\
You are an architecture reviewer evaluating a freshly-opened pull request for AI-slop signals
visible in the diff and PR content alone. There are no maintainer review comments yet — judge
from PR text, files, author signals, and retrieved project context.

SCORING RUBRIC — calibrate against these anchors:
  10 — Exemplary fit: matches naming, module structure, and abstraction patterns of nearby code; right-sized for the problem.
   8 — Clean and consistent; minor stylistic divergence at most. COMMON CASE for legitimate PRs.
   6 — Neutral. No glaring misalignment, but no positive evidence of pattern consistency.
   4 — One or more strong signals fire (see below).
   2 — Multiple strong signals fire together.
   0 — Fundamentally misaligned, contradicts retrieved patterns.

MAINTAINER-FRICTION SIGNALS (each counts toward lower score):
- Scope creep: title says X, diff also does Y unrelated.
- "Improve performance" / "clean up" PRs with no benchmarks or before/after evidence.
- Renaming or reformatting that touches files the author has never contributed to.
- New helper modules added when one-line inline code would suffice.
- Defensive code (validation, fallbacks, try/except) for situations that cannot happen.
- Generic refactors with no user-visible motivation.

OVER-ENGINEERING PATTERNS — strong AI-slop signal, cap at 4:
- New ContextVar, context manager, helper class, or registry introduced for a one-off problem
  that could be solved inline in a few lines.
- AI-explanatory comments/docstrings that read like a textbook explaining the implementation
  ("Each entry is X so that Y. Implemented as a list with append/pop so nested construction stays O(1)"),
  rather than terse comments on non-obvious WHY.
- Wrong architectural layer: workaround in module A when the root cause is clearly in module B
  (e.g., a regex shim in serialization code where the parser is the real bug).
- Adds defensive null/type-checks around values that come from the project's own well-typed code paths.

DEFAULT FLOOR — when none of the MAINTAINER-FRICTION or OVER-ENGINEERING patterns fire with
specific named evidence, the score MUST be ≥6. Do not invent friction; default to 7-8 for
normal-looking PRs that fit the diff size and project patterns.

DEFAULT POSTURE:
- Score 7–8 when the change fits the diff size and the project's normal patterns. COMMON CASE.
- Score 6 only when retrieved context truly does not establish any relevant pattern.
- A score ≤4 requires naming a specific friction signal or pattern mismatch.

OUTPUT FORMAT — strict:
Return ONLY a single JSON object, no markdown fences, no prose, no trailing text.
Escape backslashes and quotes inside string values. Keep "evidence" as a one-line paraphrase.

Schema:
{
  "score": <integer 0-10>,
  "findings": [
    {"severity": "critical"|"major"|"minor"|"info", "category": "<slug>", "evidence": "<one-line paraphrase>"}
  ],
  "citations": ["<chunk_id_string>"]
}
"""


def architecture_critic_node(state: TriageState, claude: ClaudeClient, *, model: str | None = None) -> dict:
    """Architecture critic — Sonnet in production, overridable for eval.

    First-look mode: judges from PR content + author signals + RAG. No post-hoc
    review comments or timing data.
    """
    from ai_slop_detector.claude_client import MODEL_SONNET

    chunks_text = "\n\n".join(state.rag_chunks) if state.rag_chunks else "(no context retrieved)"
    diff_preview = (state.raw_diff or "")[:6000]
    labels_str = ", ".join(state.metadata.labels) if state.metadata.labels else "(none)"
    assoc = state.metadata.author_association or "unknown"
    user_msg = (
        f"PR #{state.metadata.number}: {state.metadata.title}\n\n"
        f"PR Description:\n{state.metadata.body or '(none)'}\n\n"
        f"Author: {state.metadata.author}  (association: {assoc}, prior_prs_in_repo: {state.author_prior_prs})\n"
        f"Files changed: {', '.join(state.files_changed[:20])}\n"
        f"pr_labels: {labels_str}\n\n"
        f"Diff (first 6000 chars):\n{diff_preview}\n\n"
        f"Retrieved project context:\n{chunks_text}"
    )

    raw = claude.complete(
        messages=[{"role": "user", "content": user_msg}],
        model=model or MODEL_SONNET,
        max_tokens=2048,
        system=_ARCH_CRITIC_SYSTEM,
    )

    details = _parse_critic_json(raw)
    score = details.score
    verdict_str = "pass" if score >= 8 else "needs_review" if score >= 5 else "fail"

    output = CriticOutput(
        critic_name="architecture_critic",
        verdict=verdict_str,
        reasoning=f"Architecture score {score}/10 with {len(details.findings)} finding(s).",
        confidence=score / 10.0,
        details=details,
    )
    return {"critic_outputs": [output]}


# ------------------------------------------------------------------
# Node: slop_signals_critic (B2)
# ------------------------------------------------------------------

_SLOP_CRITIC_SYSTEM = """\
You evaluate whether a freshly-opened PR is AI slop: low-effort, AI-boilerplate, drive-by, or
cargo-cult. Maintainer reviews have not happened yet — judge from PR content, author signals,
and pre-detected body/diff heuristics only.

SCORING RUBRIC — calibrate against these anchors:
  10 — Genuine, focused contribution. Specific description; diff matches description; no slop markers.
   8 — Real work, minor presentation issues. Common case for legitimate PRs.
   6 — Borderline. Plausibly genuine but description is generic or scope is unclear.
   4 — Significant slop markers: vague description, generic AI phrases, or one strong negative signal.
   2 — Clear slop: matches one of the HARD CAPS below.
   0 — Pure boilerplate, wrong-target PR, or contribution-farm pattern.

TRUST WEIGHTING — apply BEFORE hard caps:
- If author_association is OWNER/MEMBER/COLLABORATOR, the author is a trusted maintainer.
  SKIP caps (B)–(D) below — those are drive-by / AI-slop patterns that do not apply to maintainers.
  Caps (A), (E), (F) still apply.
- If author_association is CONTRIBUTOR (has prior merged PRs), apply caps (B)–(C) only when prior_prs ≤ 5.
- If author_association is NONE or unknown AND author_prior_prs ≤ 3, treat as drive-by — full caps apply.

HARD CAPS — apply BEFORE the rubric, take the lowest cap that fires:

(A) AI-DISCLOSURE FOOTER (body contains "Generated with Claude Code", "Prepared with Codex",
    "🤖" bot footer, "Generated by GPT", or similar):
    - Non-trivial code (touches project internals or > 10 lines) → cap at 3.
    - Trivial doc/comment edit (contraction, typo) → cap at 4 (drive-by stats trawl).

(B) DRIVE-BY OVERREACH: author_prior_prs ≤ 3 AND change is large (≥80 lines) AND touches
    project internals (not user-facing API) → cap at 4.
    DOES NOT APPLY if the PR ALSO includes test files alongside the implementation OR references
    a specific issue ("Fixes #N", "Closes #N") with substantive root-cause analysis in the body.
    A first-time contributor doing real engineering with tests is not slop.

(C) DRIVE-BY TRIVIA: author_prior_prs ≤ 5 AND diff is trivial (≤5 lines, doc/comment-only)
    AND no issue linked AND no test added → cap at 4.

(D) MANIPULATIVE @-MENTION: PR body contains "Selected Reviewer:" or "Assigned Reviewer:"
    with a direct @-mention of a maintainer → cap at 3.

(E) AI-CHECKLIST THEATRE: PR body has structured headers like "## Summary", "## Related issue: N/A",
    "## Guideline alignment", "## Validation", "## AI assistance" AND change is trivial (≤10 lines) → cap at 4.

(F) WRONG-TARGET / SIBLING-REPO MISMATCH: cap at 2 — strongest slop signal.
    - If "sibling_repo_mismatch_path" in body signals is non-empty, the diff edits a file path
      that looks like a separate repo under the same org. Example: PR in "pydantic/pydantic"
      editing files under "pydantic-core/" — these are typically separate GitHub repositories
      with their own PR queues, so this PR will never merge regardless of content quality. Cap at 2.
    - Also applies when the PR title claims to fix something specific (e.g., "fix X serializer")
      but the diff doesn't touch any code related to X.

SMALL-PR RULE (≤30 changed lines, heuristic features near zero):
- Tiny PRs read zero on every heuristic feature. Do NOT treat that as evidence of quality.
- Judge by description specificity, title-vs-diff alignment, and the HARD CAPS above.
- A clean-looking small PR with a vague description scores 4–6, not 8.

HEURISTIC FEATURE INTERPRETATION (apply as score adjustments, after hard caps):
- duplicate_line_ratio > 0.3 → −2 (copy-paste pattern)
- todo_fixme_count ≥ 3 → −2
- debug_print_count ≥ 1 → −3
- ai_phrase_count ≥ 3 → −2

DEFAULT POSTURE:
- No hard cap fires AND description is specific AND diff matches → 7–9 (common case).
- No hard cap fires but description is generic → 5–7.
- A score ≥8 requires substantive description + linked issue OR test added alongside change.
- If no slop markers visible in PR content, do NOT invent friction — score 7-8.

OUTPUT FORMAT — strict:
Return ONLY a single JSON object, no markdown fences, no prose, no trailing text.
Escape backslashes and quotes inside string values. Keep "evidence" as a one-line paraphrase.

Schema:
{
  "score": <integer 0-10>,
  "findings": [
    {"severity": "critical"|"major"|"minor"|"info", "category": "<slug>", "evidence": "<one-line paraphrase>"}
  ],
  "citations": []
}
"""

# Phrases frequently found in AI-generated PR descriptions.
_AI_PHRASES = [
    "this pr ", "this pull request ", "i have implemented", "i have added",
    "feel free to ", "let me know if ", "hope this helps", "happy to make",
    "easy to understand", "improve code quality", "improve readability",
    "enhance performance", "various improvements", "minor improvements",
    "several improvements", "best practices", "clean code", "as per your request",
]

# Substrings (case-insensitive) that mark an AI-disclosure footer in a PR body.
_AI_FOOTER_MARKERS = [
    "generated with claude code", "prepared with codex", "generated by gpt",
    "generated by chatgpt", "built with ai", "🤖 generated", "co-authored-by: claude",
    "co-authored-by: codex",
]

# Section-header phrases used by AI checklist-style PR bodies.
_AI_CHECKLIST_HEADERS = [
    "## summary", "## related issue", "## guideline alignment",
    "## validation", "## ai assistance", "## change summary",
]


def _detect_body_signals(body: str) -> dict:
    """Detect slop signals visible in a PR body without needing maintainer comments."""
    b = (body or "").lower()
    ai_footer = any(m in b for m in _AI_FOOTER_MARKERS)
    manipulative_mention = ("selected reviewer:" in b or "assigned reviewer:" in b) and "@" in b
    checklist_headers = sum(1 for h in _AI_CHECKLIST_HEADERS if h in b)
    return {
        "ai_footer": ai_footer,
        "manipulative_mention": manipulative_mention,
        "ai_checklist_headers": checklist_headers,
        "body_length": len(body or ""),
    }


def _time_open_minutes(state: TriageState) -> float | None:
    """How long was the PR open, in minutes? None if still open or timestamps missing."""
    if state.closed_at is None or state.metadata.created_at is None:
        return None
    return (state.closed_at - state.metadata.created_at).total_seconds() / 60.0


def _format_comments(state: TriageState, *, max_per_kind: int = 2, max_chars: int = 400) -> str:
    """Render PR review history as a compact block for the critic prompts.

    Shows the first `max_per_kind` comments of each kind PLUS the last one when there are
    more — close-acknowledgements and final-approval phrases usually live in the trailing
    comment, and we need the model to see them. Empty sections are dropped.
    """
    parts: list[str] = []

    def render(label: str, items: list[dict]) -> None:
        if not items:
            return
        head = items[:max_per_kind]
        tail_idx = None
        # Include the trailing comment too when it isn't already in the head slice.
        if len(items) > max_per_kind:
            tail_idx = len(items) - 1
        shown = list(head)
        if tail_idx is not None and tail_idx >= len(head):
            shown.append(items[tail_idx])
        count_note = (
            f"showing first {len(head)} + last (total {len(items)})"
            if tail_idx is not None
            else f"all {len(items)}"
        )
        lines = [f"{label} ({count_note}):"]
        for idx, c in enumerate(shown):
            who = c.get("user", "?")
            assoc = c.get("author_association", "")
            body = (c.get("body") or "").strip().replace("\n", " ")
            if len(body) > max_chars:
                body = body[: max_chars - 1] + "…"
            assoc_tag = f" ({assoc})" if assoc and assoc != "NONE" else ""
            position = "LAST" if tail_idx is not None and idx == len(shown) - 1 else f"#{idx+1}"
            lines.append(f"  [{position}] [{who}{assoc_tag}]: {body}")
        parts.append("\n".join(lines))

    render("Maintainer / issue comments", state.issue_comments)
    render("Review comments (diff-line)", state.review_comments)
    render("Bot / CI comments", state.bot_comments)

    return "\n\n".join(parts) if parts else "(no comments yet)"


# Repo-short → file-path-prefix patterns that indicate a "sibling-repo wrong-target" PR
# (e.g., a PR submitted to pydantic/pydantic that edits pydantic-core/* files).
def _detect_sibling_repo_mismatch(repo: str, files: list[str]) -> str | None:
    """Return the first file path that looks like it belongs to a sibling repo, or None."""
    if "/" not in repo or not files:
        return None
    repo_short = repo.split("/", 1)[1]
    if "-" in repo_short or len(repo_short) < 3:
        return None  # e.g., "ty-internal", we can't disambiguate cleanly
    pattern = re.compile(rf"^{re.escape(repo_short)}-[A-Za-z0-9_]+/")
    for f in files:
        if isinstance(f, str) and pattern.match(f):
            return f
    return None


def _compute_sloppiness_features(state: TriageState) -> SloppinessFeatures:
    """Extract heuristic slop signals from the raw diff and PR metadata."""
    diff = state.raw_diff or ""
    body = (state.metadata.body or "").lower()
    added_lines = [ln[1:] for ln in diff.splitlines() if ln.startswith("+") and not ln.startswith("+++")]

    duplicate_line_ratio = _duplicate_ratio(added_lines)
    todo_fixme_count = sum(
        1 for ln in added_lines
        if any(kw in ln.lower() for kw in ("todo", "fixme", "hack", "xxx"))
    )
    debug_print_count = sum(
        1 for ln in added_lines
        if any(kw in ln.lower() for kw in ("print(", "console.log(", "debugger", "pdb.set_trace"))
    )
    magic_number_count = _count_magic_numbers(added_lines)
    generic_phrases = sum(1 for phrase in _AI_PHRASES if phrase in body)
    long_function_count = _count_long_added_functions(added_lines)

    return SloppinessFeatures(
        duplicate_line_ratio=duplicate_line_ratio,
        long_function_count=long_function_count,
        todo_fixme_count=todo_fixme_count,
        debug_print_count=debug_print_count,
        magic_number_count=magic_number_count,
        missing_docstring_count=generic_phrases,  # repurposed: AI phrase count
    )


def _duplicate_ratio(lines: list[str]) -> float:
    stripped = [ln.strip() for ln in lines if ln.strip()]
    if not stripped:
        return 0.0
    unique = len(set(stripped))
    return 1.0 - unique / len(stripped)


def _count_magic_numbers(lines: list[str]) -> int:
    import re
    count = 0
    for ln in lines:
        # Raw numeric literals not assigned to a named constant
        if re.search(r"(?<![a-zA-Z_\d])\d{2,}(?!\s*[=:,\)])", ln):
            count += 1
    return count


def _count_long_added_functions(lines: list[str]) -> int:
    """Count function/method definitions in added lines that span >50 added lines."""
    import re
    func_starts: list[int] = []
    for i, ln in enumerate(lines):
        if re.match(r"\s*(def |function |async def |\w+\s*\()", ln):
            func_starts.append(i)
    # Simple heuristic: if total added lines per function block > 50
    count = 0
    for i, start in enumerate(func_starts):
        end = func_starts[i + 1] if i + 1 < len(func_starts) else len(lines)
        if end - start > 50:
            count += 1
    return count


def slop_signals_critic_node(state: TriageState, claude: ClaudeClient, *, model: str | None = None) -> dict:
    """Slop critic — Sonnet in production, overridable for eval."""
    from ai_slop_detector.claude_client import MODEL_SONNET

    features = _compute_sloppiness_features(state)
    body_signals = _detect_body_signals(state.metadata.body or "")
    total_lines = state.metadata.additions + state.metadata.deletions

    feature_summary = (
        f"Heuristic features:\n"
        f"  duplicate_line_ratio: {features.duplicate_line_ratio:.2f}\n"
        f"  long_function_count: {features.long_function_count}\n"
        f"  todo_fixme_count: {features.todo_fixme_count}\n"
        f"  debug_print_count: {features.debug_print_count}\n"
        f"  magic_number_count: {features.magic_number_count}\n"
        f"  ai_phrase_count (in description): {features.missing_docstring_count}\n"
    )

    labels_str = ", ".join(state.metadata.labels) if state.metadata.labels else "(none)"
    assoc = state.metadata.author_association or "unknown"
    author_signals = (
        f"Author signals:\n"
        f"  author: {state.metadata.author}\n"
        f"  author_association: {assoc}\n"
        f"  author_prior_prs_in_repo: {state.author_prior_prs}\n"
        f"  total_changed_lines: {total_lines}\n"
        f"  files_changed: {state.metadata.changed_files}\n"
        f"  pr_labels: {labels_str}\n"
    )

    sibling_path = _detect_sibling_repo_mismatch(state.repo, state.files_changed)
    body_signal_summary = (
        f"Body signals (pre-detected):\n"
        f"  ai_disclosure_footer_present: {body_signals['ai_footer']}\n"
        f"  manipulative_reviewer_mention: {body_signals['manipulative_mention']}\n"
        f"  ai_checklist_headers_count: {body_signals['ai_checklist_headers']}\n"
        f"  body_length_chars: {body_signals['body_length']}\n"
        f"  sibling_repo_mismatch_path: {sibling_path or '(none)'}\n"
    )

    diff_preview = (state.raw_diff or "")[:4000]
    files_list = "\n".join(f"  - {p}" for p in state.files_changed[:15])
    user_msg = (
        f"PR #{state.metadata.number} in {state.repo}: {state.metadata.title}\n\n"
        f"PR Description:\n{state.metadata.body or '(none)'}\n\n"
        f"{author_signals}\n"
        f"{body_signal_summary}\n"
        f"{feature_summary}\n"
        f"Files changed (first 15):\n{files_list or '  (none)'}\n\n"
        f"Diff (first 4000 chars):\n{diff_preview}"
    )

    raw = claude.complete(
        messages=[{"role": "user", "content": user_msg}],
        model=model or MODEL_SONNET,
        max_tokens=1024,
        system=_SLOP_CRITIC_SYSTEM,
    )

    details = _parse_critic_json(raw)
    score = details.score
    verdict_str = "pass" if score >= 8 else "needs_review" if score >= 5 else "fail"

    output = CriticOutput(
        critic_name="slop_signals_critic",
        verdict=verdict_str,
        reasoning=f"Slop score {score}/10 with {len(details.findings)} finding(s).",
        confidence=score / 10.0,
        details=details,
    )
    return {
        "sloppiness_features": features,
        "critic_outputs": [output],
    }


# ------------------------------------------------------------------
# Node: aggregate (replaces emit_verdict for Phase 3+)
# ------------------------------------------------------------------

def aggregate_node(state: TriageState) -> dict:
    """Deterministic multi-critic aggregator node.

    Combines all critic outputs via the aggregator module.
    Writes both aggregate_result (Phase 3) and the backward-compatible
    aggregate_verdict (Phase 2 field).
    """
    from ai_slop_detector.aggregator import aggregate

    result = aggregate(state.critic_outputs)

    verdict = Verdict(
        decision=result.decision,
        summary=result.summary,
        confidence=result.confidence,
    )
    return {
        "aggregate_verdict": verdict,
        "aggregate_result": result,
    }


# Keep emit_verdict_node as an alias for backward compatibility with Phase 2 tests.
emit_verdict_node = aggregate_node
