from __future__ import annotations

import json
import re
from datetime import datetime, timedelta
from pathlib import Path

_SILENT_SLOP_MIN_LINES = 20
_SILENT_SLOP_MAX_LINES = 500
_SILENT_SLOP_MAX_PRIOR_PRS = 3
_MAINTAINER_WINDOW_HOURS = 24

# AI disclosure / mention — only fires on closed-unmerged PRs
_AI_KEYWORD_RE = re.compile(
    r"\b(AI-generated|AI-assisted|ChatGPT|Copilot|Codex|Claude|slop|AI usage|"
    r"generated by AI|written by AI|Generated with Claude Code|Co-Authored-By: Claude)\b",
    re.IGNORECASE,
)

# Maintainer phrases that explicitly reject a PR
_REJECTION_PHRASE_RE = re.compile(
    r"AI policy|violating our (?:policy|policies)|AI[- ]generated|drive-by|"
    r"did you write this yourself|please read CONTRIBUTING|"
    r"read the (?:instructions|guidelines|policy)|did you actually test|"
    r"out of scope|not accepted|procedures not followed|bot spam",
    re.IGNORECASE,
)

# CONTRIBUTOR is included because many repo founders/core maintainers are
# harvested with that association (e.g. mitchellh on ghostty-org/ghostty,
# dimbleby on python-poetry/poetry) despite having maintainer authority.
_MAINTAINER_ASSOCIATIONS = frozenset({"MEMBER", "OWNER", "COLLABORATOR", "CONTRIBUTOR"})


def prelabel_candidate(candidate: dict) -> dict:
    """Assign a heuristic pre-label to a single PR candidate dict.

    Returns {"is_slop_likely": bool, "label": str, "confidence": str, "signals": list[str]}.

    The binary `is_slop_likely` is the primary output for downstream consumers.
    The legacy 3-class `label` is kept so the human labeler can show a finer-grained
    suggestion (accepted vs rejected_quality) for not-slop PRs:

      accepted         — merged PR (high confidence; is_slop_likely=False)
      slop             — closed-unmerged + one or more slop signals (is_slop_likely=True)
      rejected_quality — closed-unmerged + maintainer comment, no slop signal (is_slop_likely=False)
      unclear          — closed-unmerged, no comments, no slop signal (is_slop_likely=False)

    Slop confidence stacks by signal count: 1 → low, 2 → medium, 3+ → high.
    """
    merged = candidate.get("merged", False)
    closed_at = candidate.get("closed_at")
    additions = candidate.get("additions", 0)
    deletions = candidate.get("deletions", 0)
    total_lines = additions + deletions
    prior_prs = candidate.get("author_prior_prs_in_repo")
    issue_comments = candidate.get("issue_comments", [])
    review_comments = candidate.get("review_comments", [])
    body = candidate.get("body") or ""
    all_comments = issue_comments + review_comments

    if merged:
        return {"is_slop_likely": False, "label": "accepted", "confidence": "high", "signals": []}

    slop_signals: list[str] = []

    # Signal 1: AI disclosure or mention in body / discussion thread (closed-unmerged only)
    if closed_at:
        ai_text = body + " " + " ".join(c.get("body", "") or "" for c in issue_comments)
        if _AI_KEYWORD_RE.search(ai_text):
            slop_signals.append("ai_disclosure_or_mention")

    # Signal 2: Silent slop — no engagement, first-timer, moderate size
    if (
        closed_at
        and len(all_comments) == 0
        and prior_prs is not None
        and prior_prs <= _SILENT_SLOP_MAX_PRIOR_PRS
        and _SILENT_SLOP_MIN_LINES <= total_lines <= _SILENT_SLOP_MAX_LINES
    ):
        slop_signals.append("silent_slop_pattern")

    # Signal 3: Maintainer explicitly cited policy/rejection within 24h of close
    if closed_at:
        _check_maintainer_explicit(candidate, closed_at, slop_signals)

    if slop_signals:
        n = len(slop_signals)
        confidence = "low" if n == 1 else ("medium" if n == 2 else "high")
        return {"is_slop_likely": True, "label": "slop", "confidence": confidence, "signals": slop_signals}

    if _has_maintainer_comment(all_comments):
        return {"is_slop_likely": False, "label": "rejected_quality", "confidence": "medium", "signals": []}

    return {"is_slop_likely": False, "label": "unclear", "confidence": "low", "signals": []}


def _has_maintainer_comment(comments: list[dict]) -> bool:
    return any(c.get("author_association") in _MAINTAINER_ASSOCIATIONS for c in comments)


def _check_maintainer_explicit(
    candidate: dict, closed_at_str: str, signals: list[str]
) -> None:
    """Append 'maintainer_explicit_rejection' if a qualifying comment exists near close time."""
    try:
        closed_dt = datetime.fromisoformat(closed_at_str.replace("Z", "+00:00"))
    except Exception:
        return

    window = timedelta(hours=_MAINTAINER_WINDOW_HOURS)
    all_comments = candidate.get("issue_comments", []) + candidate.get("review_comments", [])
    for c in all_comments:
        if c.get("author_association") not in _MAINTAINER_ASSOCIATIONS:
            continue
        created = c.get("created_at")
        if not created:
            continue
        try:
            ct = datetime.fromisoformat(created.replace("Z", "+00:00"))
        except Exception:
            continue
        if abs(ct - closed_dt) <= window:
            if _REJECTION_PHRASE_RE.search(c.get("body") or ""):
                signals.append("maintainer_explicit_rejection")
                return


def prelabel_dir(
    candidates_dir: Path,
    out_path: Path,
    *,
    verbose: bool = False,
) -> int:
    """Pre-label all candidate JSON files and write JSONL to out_path.

    Each output line: {repo, pr_number, title, additions, deletions, label, confidence, signals}.
    Returns the number of entries written.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)
    count = 0

    with out_path.open("w") as fout:
        for candidate_file in sorted(candidates_dir.glob("*.json")):
            try:
                candidate = json.loads(candidate_file.read_text())
            except Exception:
                continue
            if "pr_number" not in candidate:
                continue

            result = prelabel_candidate(candidate)
            entry = {
                "file": candidate_file.name,
                "repo": candidate.get("repo", ""),
                "pr_number": candidate.get("pr_number"),
                "title": candidate.get("title", ""),
                "additions": candidate.get("additions", 0),
                "deletions": candidate.get("deletions", 0),
                "changed_files_count": candidate.get("changed_files", 0),
                "is_slop_likely": result["is_slop_likely"],   # binary primary
                "label": result["label"],                      # legacy 3-class hint for the labeler
                "confidence": result["confidence"],
                "signals": result["signals"],
            }
            fout.write(json.dumps(entry) + "\n")
            if verbose:
                sigs = ",".join(result["signals"]) if result["signals"] else "-"
                binary = "slop" if result["is_slop_likely"] else "not-slop"
                print(f"  {candidate_file.name}: {binary} ({result['confidence']}) [legacy={result['label']}, {sigs}]")
            count += 1

    return count
